### ISSUE TITLE
IOException: Connection reset by peer

### ISSUE THREAD

**Issue by freizl** [kouxing2000/kingfisher#2]
This exception is very likely to occur. Though it's not big deal (no impacting proxy most of time), might address when have time.
 
```
25597  2015-03-17 08:54:32,380 WARN  [LittleProxy-ClientToProxyWorker-7] impl.ClientToProxyConnection (?:?).?() - (AWAITING_INITIAL {tunneling}) [id: 0xdda9c38f, /127.0.0.1:38886 => /127.0.0.1:8081]: Caught an exception on ClientToProxyConnection
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:446)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:871)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:118)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by kouxing2000** [comment]
Let's see whether we can just mute it. :)

**Comment by freizl** [comment]
Do you know what's the root cause?

**Comment by kouxing2000** [comment]
@Override
    protected void exceptionCaught(Throwable cause) {
        String message = "Caught an exception on ClientToProxyConnection";
        boolean shouldWarn = cause instanceof ClosedChannelException ||
                cause.getMessage().contains("Connection reset by peer"); 
        if (shouldWarn) {
            LOG.warn(message, cause);
        } else {
            LOG.error(message, cause);
        }
        disconnect();
    }

I can mute it, just a debug level log. Commit code immediately.

**Comment by freizl** [comment]
Cool.
So it doesn't affect functionality at all?

**Comment by kouxing2000** [comment]
no. not at all.
